webtalk_init -webtalk_dir C:/Users/33651/Desktop/test_ajc/TP/TP3_FSM/TP3_FSM.sim/sim_1/behav/xsim/xsim.dir/tb_tp_fsm_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul 16 11:29:40 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c2149717-cd8c-4f8a-afa2-94c1be52bdda" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "75dea1669dca4fcaa158698bbd52aa9c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "85" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3700X 8-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3593 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "181106175 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "16.98_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16860_KB" -context "xsim\\usage"
webtalk_transmit -clientid 798485135 -regid "" -xml C:/Users/33651/Desktop/test_ajc/TP/TP3_FSM/TP3_FSM.sim/sim_1/behav/xsim/xsim.dir/tb_tp_fsm_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/33651/Desktop/test_ajc/TP/TP3_FSM/TP3_FSM.sim/sim_1/behav/xsim/xsim.dir/tb_tp_fsm_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/33651/Desktop/test_ajc/TP/TP3_FSM/TP3_FSM.sim/sim_1/behav/xsim/xsim.dir/tb_tp_fsm_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
